const keywords = ['mobile tracker',
'spyware',
'phone tracker',
'keylogger',
'track phone number',
'sms tracker',
'spy phone app',
'cell phone tracker',
'blue whale game',
'key logger',
'track iphone',
'track phone location',
'spy apps',
'phone tracker app',
'spy app',
'whatsapp hack',
'phone spy',
'iphone jailbreak',
'mobile phone tracker',
'phone location tracker',
'keylogger for android',
'mobile spy',
'iphone spy app',
'how to track an android phone',
'keylogger android',
'spy phone',
'android phone tracker',
'spy bubble',
'spy software',
'android keylogger',
'iphone keylogger',
'spy on phone',
'best spy app',
'whatsapp spy',
'cell phone location tracker',
'android spy',
'track cell phone location',
'spy app for iphone',
'spy on iphone',
'cell phone spy software',
'keylogger for iphone',
'snapchat spy',
'spyware for iphone',
'whatsapp tracker',
'whatsapp sniffer',
'how to monitor snapchat',
'cell phone monitoring',
'cell phone spy',
'iphone spy app no jailbreak',
'spy software for iphone',
'spyphone app',
'mobile tracking',
'how to spy on iphone',
'iphone spy',
'best spyware for android',
'track cell phone number',
'spy apps for iphone',
'mobilespy',
'best spy app for iphone',
'stealthgenie',
'iphone spyware',
'how to intercept text messages',
'phone spy apps',
'spymobile',
'android spy software',
'spy to mobile',
'spymaster pro',
'cell spy',
'top spy',
'best iphone spy apps',
'spy cell phone',
'bosspy',
'phone spy software',
'hellospy',
'iphone spy software',
'cell phone tracking software',
'spy iphone without jailbreak',
'keylogger iphone',
'monitor snapchat',
'spy iphone',
'xnore spy app',
'mobile spy app',
'track someone phone',
'gps cell phone',
'hidden sms tracker',
'phone tracking software',
'track mobile phone',
'topspy',
'flexi spy',
'how to spy on cell phone',
'spyware on iphone',
'spyware for iphone without jailbreaking',
'sms tracker for iphone',
'best spyware for iphone',
'iphone spy no jailbreak',
'spy phone software',
'spy mobile',
'spy whatsapp',
'maxxspy',
'tracking someones phone',
'spy cell',
'spy sms',
'phone tracker android',
'1topspy',
'how to spy on text messages',
'spy app iphone',
'spy software for android',
'sms tracker hidden',
'phone call tracker',
'best spy apps for iphone',
'facebook messenger spy',
'phonty',
'buscar telefono por gps',
'sms spy',
'see facebook',
'how track iphone',
'monitoring text messages',
'iphone spy without jailbreak',
'spy mobile app',
'snapchat tracking',
'mobile phone spy',
'cell phone trackers',
'iphone message spy',
'viber spy',
'best iphone spy',
'spy mobile phone',
'ios keylogger',
'top android spy apps',
'track someones phone',
'read facebook',
'app parental control',
'keylogger app for android',
'localizar telefono por gps',
'spy software android',
'snapchat monitor',
'spy phone android',
'spy stealth',
'spy software iphone',
'best app for parental control',
'spy text messages iphone',
'how can i monitor snapchat',
'track snapchat',
'spyware iphone',
'mobile-spy',
'sms spy without target phone free',
'best free android spy apps',
'parent phone monitoring app',
'monitor messages iphone',
'ubicar telefono por gps',
'1 topspy',
'best spy for iphone',
'app android spy',
'phone parental monitoring',
'cell monitoring software',
'iphone spy tracking']

module.exports = keywords
